.TH NR-CONFIG 5
.SH NAME
nr-config \- the nr config file
.SH SYNOPSIS
.I nr.ini
.TP
.I ~/.config/nr.ini
.SH DESCRIPTION
This manual page describes the format of the \fInr.ini\fR file.
.SH CONFIGURATION FILE
.BR
.EX
[newsreader]
width = 40
align = center
sites = https://text.npr.org/
.SH AUTHOR
Written by Trevor Bramwell <\fItrevor@bramwell.net\fR>
.SH "SEE ALSO"
.BR nr (1)
